### ISSUE TITLE
Error on compiling blocks

### ISSUE THREAD

**Issue by bph** [ryanwelcher/create-block-multple-blocks-template#4]
Just ran the command: `npx @wordpress/create-block pollv2 --template @ryanwelcher/multiple-blocks-template` 

It all ran well until the "Compiling block" step.  It  ran into the following error: 
`(node:13589) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 2: npm run build
[webpack-cli] Failed to load '/Users/birgitpauli-haack/Local Sites/learning-blocks/app/public/wp-content/plugins/pollv2/webpack.config.js' config
[webpack-cli] TypeError: MiniCSSExtractPlugin is not a constructor
    at Object.<anonymous> (/Users/birgitpauli-haack/Local Sites/learning-blocks/app/public/wp-content/plugins/pollv2/node_modules/@wordpress/scripts/config/webpack.config.js:240:3)`
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/birgitpauli-haack/Local Sites/learning-blocks/app/public/wp-content/plugins/pollv2/webpack.config.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR! code 2
npm ERR! path /Users/birgitpauli-haack/Local Sites/learning-blocks/app/public/wp-content/plugins/pollv2
npm ERR! command failed
npm ERR! command sh -c wp-scripts build
---
Then it continued with: 
> pollv2@0.1.0 build
> wp-scripts build

    at makeError (/Users/birgitpauli-haack/.npm/_npx/0890e296436e9575/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/birgitpauli-haack/.npm/_npx/0890e296436e9575/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/Users/birgitpauli-haack/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/init-wp-scripts.js:31:2)
    at async module.exports (/Users/birgitpauli-haack/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/scaffold.js:103:3)
    at async Command.<anonymous> (/Users/birgitpauli-haack/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/index.js:91:6)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13589) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
---

**Comment by bph** [comment]
Closing again. Seems to be a problem upstream in @wordpress/create-block and I ran into the same and other error message on `npx @wordpress/create-block` command as well.
